// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package models

import (
	"context"
)

type Querier interface {
	AddUser(ctx context.Context, arg AddUserParams) error
	DeleteUser(ctx context.Context, userID int64) error
	GetAnimeByID(ctx context.Context, animeID int64) (Animation, error)
	GetAnimesByCountry(ctx context.Context, arg GetAnimesByCountryParams) ([]Animation, error)
	GetAnimesByIDs(ctx context.Context, ids []int64) ([]Animation, error)
	GetAnimesByRelease(ctx context.Context, arg GetAnimesByReleaseParams) ([]Animation, error)
	GetAnimesByType(ctx context.Context, arg GetAnimesByTypeParams) ([]AnimationGenre, error)
	GetListAnimes(ctx context.Context, arg GetListAnimesParams) ([]Animation, error)
	GetUser(ctx context.Context, userID int64) (User, error)
	InsertAnime(ctx context.Context, arg InsertAnimeParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) error
}

var _ Querier = (*Queries)(nil)
