CREATE TABLE IF NOT EXISTS anime (
    `aid` INT NOT NULL AUTO_INCREMENT COMMENT '动画 id' PRIMARY KEY,
    `image` VARCHAR(255) COMMENT '动画封面图',
    `title` VARCHAR(255) COMMENT '动画标题',
    `sorce` FLOAT COMMENT '推荐指数',
    `desc`  TEXT COMMENT '简介',
    `tag` VARCHAR(255) COMMENT '标签',
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间'
);