// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package models

import (
	"context"
)


type Querier interface {
	AddAnime(ctx context.Context, arg AddAnimeParams) error
	DeleteAnime(ctx context.Context, animeID int64) error
	GetAnime(ctx context.Context, animeID int64) (Animation, error)
	GetListAnimes(ctx context.Context, arg GetListAnimesParams) ([]Animation, error)
	UpdateAnime(ctx context.Context, arg UpdateAnimeParams) error
}

var _ Querier = (*Queries)(nil)
