[mysql]
user = "root"
host = "localhost"
port = 3306
password = 123456
database = "anilismei"


[server]
port = 8081

[log]
filename = "server.log"  # 日志文件输出位置
maxsize = 10                # 文件最大缓存
maxbackup = 5   
maxage = 30
conmpress = false           # 是否压缩

